### ISSUE TITLE
Plex channels fail

### ISSUE THREAD

**Issue by moonbairn** [dtankdempse/free-iptv-channels#2]
I'm using https://tinyurl.com/multiservice21?region=us&service=Plex  in TiviMate.

Playlist, Groups and EPG process and load properly, however I get an error 403 or 530 on vast majority of channels.  A few channels will work but then throw the errors after a minute or so.

Thanks for doing this work for the community.

**Comment by dtankdempse** [comment]
This issue should be reported to [matthuisman](https://github.com/matthuisman)  as my script simply converts Matt's JSON files into an M3U8 format and has no control over the requests made from his server to Plex. When I tested it, I received a "429 Too Many Requests" error, which means the server is receiving too many requests in a short period.

It’s possible that Plex is limiting the number of token requests Matt's server can make, which are required to stream content. Hopefully, Matt will be able to address this.

In the meantime, you might want to check out [plex-for-channels](https://github.com/dtankdempse/plex-for-channels) as an alternative. These requests are localized and less likely to be blocked in the same way.

**Comment by moonbairn** [comment]
Thanks for the response.  This makes sense.  Samsung is slower than usual too.

I would love to learn Docker but need to study more and don't know the major outline of what would be required.  If I can learn it would be great to be more independent.

**Comment by Toei79** [comment]
true plex getting 429 in my case 
and samsung illegalStateException

**Comment by dtankdempse** [comment]
Just did an update for Plex.
