### ISSUE TITLE
SamsungTVPlus Unsolved Mysteries glitch after commercial is done

### ISSUE THREAD

**Issue by ttx99** [dtankdempse/free-iptv-channels#29]
it looks like this has audio but video is like this
![1](https://github.com/user-attachments/assets/12d6d8b2-bf85-4bf4-a656-c1b5f1fa15ab)

Group Crime>Unsolved Mysteries

**Comment by pucknbass** [comment]
that your player some of them do that on these type of channels for commercials ... nothing the dev can do ... i dont understand what you are expecting someone to do for you here

**Comment by ttx99** [comment]
thx.
