### ISSUE TITLE
Tubi Live Channels?

### ISSUE THREAD

**Issue by BuddyChewChew** [dtankdempse/free-iptv-channels#5]
Is there anyway to get Tubi Live Channels added to this? Or do you know maybe were I could get a script or repo that runs it. The link I use to use got taken down. Im running your script on google and just wanted to say, thanks.

**Comment by dtankdempse** [comment]
I haven't looked into adding Tubi yet. I'll check it out next week if I get time. There's a Docker image by jgomez177 – his repo is here: https://github.com/jgomez177/tubi-for-channels

**Comment by BuddyChewChew** [comment]
Thanks, I don't run have docker. Im new to alot of this. But I've been using Tivimate for a couple years. I know how to install scripts and just installed Python yesterday. lol

Thanks for your time.

**Comment by dtankdempse** [comment]
This has been added https://github.com/dtankdempse/tubi-m3u

**Comment by BuddyChewChew** [comment]
OMG Thank you.
