### ISSUE TITLE
tvg-name

### ISSUE THREAD

**Issue by C-O-D** [dtankdempse/free-iptv-channels#7]
Hey, could you kindly add 'tvg-name' entries or make them optional? My app on Linux doesn't recognize the channel names otherwise...

**Comment by dtankdempse** [comment]
I've added tvg-name to the hosted script. I'll add tvg-name to Tubi and the other scripts tomorrow.

**Comment by C-O-D** [comment]
Wow, thank you so much for the super-fast response - and on a Sunday! 
Best regards 🙏

**Comment by dtankdempse** [comment]
This is been fully added now.
