### ISSUE TITLE
PBSKids and PBS

### ISSUE THREAD

**Issue by Dude138** [dtankdempse/free-iptv-channels#8]
PBSkids loads the regular PBS channels with no info and plays only one channel.  The PBS doesn't load and just gives tinyurl link info txt only when adding the playlist in TIVIMATE.

**Comment by dtankdempse** [comment]
Both playlists are generated from [matthuisman's](https://github.com/matthuisman/i.mjh.nz) JSON file, which currently duplicates the same channel for PBS Kids, as seen [here](https://i.mjh.nz/PBS/.kids_app.json). This issue should be reported to Matt.

The PBS playlist has been corrected in the hosted script (tiny URL), and I'll be updating the other scripts shortly. Thanks for bringing this to my attention!

**Comment by Dude138** [comment]
Thank you
